server:
  port: 10023
swagger:
  host: 127.0.0.1:8110
  enable: true
spring:
  datasource:
    name: MySQL
    url: jdbc:mysql://192.168.199.45:3306/wallet_2_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test_all
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 1000
    minIdle: 5
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true
  redis:
    database: 0          # Redis数据库索引（默认为0）
    host: 192.168.199.72  # Redis服务器地址
    password:            # Redis服务器连接密码（默认为空）
    port: 36379           # Redis服务器连接端口
    jedis:
      pool:
        max-idle: 8    # 连接池最大连接数
        min-idle: 1    # 连接池中的最小空闲连接
        max-active: 8  # 连接池中的最大空闲连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        timeout: 10000  # 连接超时时间（毫秒）

logging:
  config: classpath:logs.xml
  level:
    com.jinglitong.springshop.mapper: debug

#阿里云
aliyun:
  mail:
    accessKey: LTAIwhiWFBrVVCCe
    secret: FSf8fEcVKVQHnT5kQs9xLBc7l1LHI4
    regionId: cn-hangzhou
    accountName: wallet@dabtland.cn