server:
  port: 8088
spring:
  datasource:
    name: MySQL
    url: jdbc:mysql://192.168.199.86:3306/PUB_WALLET_M?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ddb_dev
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 1000
    minIdle: 5
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true
  redis:
    database: 0          # Redis数据库索引（默认为0）
    host: 192.168.199.72  # Redis服务器地址
    password:            # Redis服务器连接密码（默认为空）
    port: 36379           # Redis服务器连接端口
    jedis:
      pool:
        max-idle: 8    # 连接池最大连接数
        min-idle: 1    # 连接池中的最小空闲连接
        max-active: 8  # 连接池中的最大空闲连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        timeout: 10000  # 连接超时时间（毫秒）

swagger:
    host: 127.0.0.1:8088
    enable: true
logging:
    config: classpath:logs.xml
    level:
         com.jinglitong.springshop.mapper: debug
 #阿里云
aliyun:
    oss:
      accessKey: LTAI4GrHPh3iQ696
      secretKey: Wr6rGJH3gYoB1kfC4EEcvJ14TGBi2q
      endPoint: oss-cn-hangzhou.aliyuncs.com
      bucket: jingtongceshiqianbao
      domain: http://jingtongceshiqianbao.oss-cn-hangzhou.aliyuncs.com
    #ali邮箱
    mail:
      accessKey: LTAIwhiWFBrVVCCe
      secret:  FSf8fEcVKVQHnT5kQs9xLBc7l1LHI4
      regionId: cn-hangzhou
      accountName: wallet@dabtland.cn
       ##########rabbitmq配置##########
    mq:
      accessKey: LTAID9WuJzY52Bo8
      secretKey: ICYBMeD7NyjqzGwFlsH1GjFgMFc8Sk
      server.addr: http://MQ_INST_1383127512168997_BalJMFxY.mq-internet-access.mq-internet.aliyuncs.com:80
      order.rewardproduct: GID_SHOP_REWARD_P 
      order.topic: DDB_TEST_MQ
      orderreward.tag: tag_orderreward
      order.chinarewardproduct: GID_CHI_ORDERFINISH
      orderreward.chinatag: tag_chinaorderreward
      order.nonepaynotice.group: GID_NONEPAY_NOTICE
      order.nonepaynotice.tag: tag_nonepaynotice  

#总账支付邮件账户
payAcc_email_address: yaoxl@dabland.cn
#总账支付最小额度提醒
payAcc.amount: 10000

#订单过期和自动收货、上链信息检索
order:
    expire:
        open: 0
        cron: 0 0/1 * * * ?
    complitecorn:
        open: 0
        cron: 0 0/3 * * * ?
#重试放入到mq job
mq:
    job:
        open: 0
        cron: 0 0/1 * * * ?
#用户交易记录需要显示订单号的realName
integral:
    cust:
        record: djb_ddjl,swtc_ddjl,djb_ddzf,djb_ddch,xjd_ddzf,xjd_ddch
